# Generated by Django 2.2.4 on 2019-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190821_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='article_image', upload_to='articles/'),
        ),
    ]
